### PR TITLE
feat(visibility): change visibility for some fields

### PR DESCRIPTION
**Pull request by Gounlaf**
make chunksCount public
make isTouched private settable

### CODE REVIEW

**Comment by alxrm** [comment]
I guess `isTouched` was settable before, since it was `var`, but nvm, thanks for contribution, making `chunksCount` public makes sense tho

**Comment by Gounlaf** [comment]
About `isTouched`, I think it should be done via a Listener.
And add the property `isTouchable`? I would like to disable the "touchable" feature

**Comment by alxrm** [comment]
@Gounlaf Thought about it as well, alright, I'll add it if you haven't done this yet 😉

**Comment by alxrm** [comment]
I think I'll issue a new release with `isTouchable` and your changes together, is that okay for you?

**Comment by Gounlaf** [comment]
> @Gounlaf Thought about it as well, alright, I'll add it if you haven't done this yet 😉
> I think I'll issue a new release with isTouchable and your changes together, is that okay for you?

I was writing an issue before make a PR xD
I haven't started it yet, but I can do it within the hour

**Comment by alxrm** [comment]
@Gounlaf I did it already, nvm

**Comment by Gounlaf** [comment]
> @Gounlaf I did it already, nvm

Well, I will wait for your updates @alxrm ;) Thanks!

**Comment by alxrm** [comment]
@Gounlaf, I drafted a new [release](https://github.com/alxrm/audiowave-progressbar/releases/tag/0.9.2) including your changes

**Pull request merged**
