### PR TITLE
Fix code style.

### PR DESCRIPTION
**Pull request by bernaferrari**
My eyes hurt when I saw it, so I fixed.

Also a question, wouldn't it be better to use @JvmOverloads on AudioWaveView and replace inflateAttrs with init?

### CODE REVIEW

**Comment by alxrm** [comment]
Now that kind of PR I wanted this whole time! Thanks a lot, good sir, got me laughing 👍

It's actually a common style for functional languages AFAIC, but certainly not for kotlin

Regarding @JvmOverloads, it's nice to have it for secondary constructor, since I'm not accepting primary constructor here, it's just too ugly 🤷‍♀️

**Comment by alxrm** [comment]
And since we're all here, just wanted to say *sas* to everyone reading this thread

**Comment by bernaferrari** [comment]
If you include the @JvmOverloads you can convert all constructors to primary (https://github.com/bernaferrari/EmojiSlider/blob/d4fae80056c1ccffbaa77f20a56f973cf302d59f/emojislider/src/main/java/com/bernaferrari/emojislider/EmojiSlider.kt#L21), it is a lot better in code readability.

**Comment by alxrm** [comment]
@bernaferrari Seems like a matter of taste, I don't think it's a lot more readable, thus, as I said before, not going to accept primary constructor

Although I have nothing against @JvmOverloads for the secondary constructor

**Pull request merged**
